In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot

In [2]:
## Análise descritiva dos dados

In [3]:
base = 'Base_ScoreCredito_QuantumFinance(8).csv'

In [4]:
df = pd.read_csv(base, sep = ';')

In [5]:
df.head()

,id,idade,sexo,estado_civil,escola,Qte_dependentes,tempo_ultimoservico,trabalha,vl_salario_mil,reg_moradia,casa_propria,vl_imovel_em_mil,Qte_cartoes,Qte_carros,SCORE_CREDITO
0,708082083,45,F,casado,graduacao,3,40,1,"40,089665024322",3,0,0,1,1,778
1,708083283,58,M,solteiro,ensino fundam,0,44,1,"66,557645274838",3,0,0,1,0,"276,3"
2,708084558,46,M,divorciado,doutorado,3,35,1,"123,68182089138",6,0,0,1,1,401
3,708085458,34,F,solteiro,mestrado,0,22,1,"19,7159343168329",6,0,0,1,0,"347,4"
4,708086958,49,F,casado,mestrado,2,36,0,0,3,1,437,1,2,476

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10127 entries, 0 to 10126
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   10127 non-null  int64
 1   idade                10127 non-null  int64
 2   sexo                 10127 non-null  str
 3   estado_civil         10127 non-null  str
 4   escola               10127 non-null  str
 5   Qte_dependentes      10127 non-null  int64
 6   tempo_ultimoservico  10127 non-null  int64
 7   trabalha             10127 non-null  int64
 8   vl_salario_mil       10127 non-null  str
 9   reg_moradia          10127 non-null  int64
 10  casa_propria         10127 non-null  int64
 11  vl_imovel_em_mil     10127 non-null  int64
 12  Qte_cartoes          10127 non-null  int64
 13  Qte_carros           10127 non-null  int64
 14  SCORE_CREDITO        10127 non-null  str
dtypes: int64(10), str(5)
memory usage: 1.2 MB

In [7]:
df.describe()

,id,idade,Qte_dependentes,tempo_ultimoservico,trabalha,reg_moradia,casa_propria,vl_imovel_em_mil,Qte_cartoes,Qte_carros
count,1.012700e+04,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000,10127.000000
mean,7.391776e+08,46.325960,1.547447,34.133208,0.911919,3.783450,0.352424,208.999111,1.083638,0.623383
std,3.690378e+07,8.016814,1.489079,8.221428,0.283427,1.580486,0.477749,378.495229,0.333784,0.569796
min,7.080821e+08,26.000000,0.000000,7.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000
25%,7.130368e+08,41.000000,0.000000,30.000000,1.000000,3.000000,0.000000,0.000000,1.000000,0.000000
50%,7.179264e+08,46.000000,1.000000,34.000000,1.000000,4.000000,0.000000,0.000000,1.000000,1.000000
75%,7.731435e+08,52.000000,3.000000,39.000000,1.000000,5.000000,1.000000,289.000000,1.000000,1.000000
max,8.283431e+08,73.000000,5.000000,57.000000,1.000000,6.000000,1.000000,1800.000000,4.000000,2.000000

In [10]:
df.isnull().sum()

id                     0
idade                  0
sexo                   0
estado_civil           0
escola                 0
Qte_dependentes        0
tempo_ultimoservico    0
trabalha               0
vl_salario_mil         0
reg_moradia            0
casa_propria           0
vl_imovel_em_mil       0
Qte_cartoes            0
Qte_carros             0
SCORE_CREDITO          0
dtype: int64